# Generated by Django 3.0.8 on 2020-08-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='room_number',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
