# Generated by Django 3.0.8 on 2020-08-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20200821_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentitem',
            old_name='Dorm',
            new_name='dorm',
        ),
        migrations.RenameField(
            model_name='rentitem',
            old_name='User',
            new_name='user',
        ),
    ]
