# Generated by Django 3.0.8 on 2020-08-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_auto_20200821_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentitem',
            name='rentHour',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='rentitem',
            name='rentalDate',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='rentitem',
            name='returnHour',
            field=models.TimeField(default=None),
        ),
    ]
