# Generated by Django 3.0.8 on 2020-08-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_auto_20200821_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentitem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
