# Generated by Django 3.0.8 on 2020-11-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
