# Generated by Django 3.0.8 on 2020-11-03 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20200809_1713'),
        ('rental', '0009_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isAvailable', models.BooleanField(default=True)),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Dorm')),
            ],
        ),
    ]
