# Generated by Django 3.0.8 on 2020-11-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_item_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentitem',
            name='itemName',
        ),
        migrations.AddField(
            model_name='rentitem',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rental.Item'),
        ),
    ]
