# Generated by Django 3.0.8 on 2021-01-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_auto_20201114_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentitem',
            name='dorm',
        ),
    ]
