# Generated by Django 3.0.8 on 2020-08-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dorm_associative_Oraganaizor',
            new_name='associate_with_Dorm',
        ),
    ]
