# Generated by Django 3.0.8 on 2020-08-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200809_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='associate_with_Dorm',
            new_name='associate_with_Dorms',
        ),
    ]
