# Generated by Django 3.0.8 on 2021-01-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0002_breakdowns_rentaldate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breakdowns',
            old_name='rentalDate',
            new_name='requestDate',
        ),
    ]
