# Generated by Django 3.0.8 on 2020-08-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Dorm_associative_Oraganaizor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dorm', models.ForeignKey(on_delete=models.SET(0), to='security.Dorm')),
                ('id_oraganization', models.ForeignKey(on_delete=models.SET(0), to='security.Organization')),
            ],
        ),
    ]
