# Generated by Django 3.0.8 on 2020-08-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_dorm_dorm_associative_oraganaizor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dorm_associative_oraganaizor',
            old_name='id_oraganization',
            new_name='id_organization',
        ),
    ]
