# Generated by Django 3.0.8 on 2020-08-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20200808_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dorm_associative_oraganaizor',
            name='id_dorm',
        ),
        migrations.RemoveField(
            model_name='dorm_associative_oraganaizor',
            name='id_organization',
        ),
        migrations.DeleteModel(
            name='Dorm',
        ),
        migrations.DeleteModel(
            name='Dorm_associative_Oraganaizor',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
