# Generated by Django 3.0.8 on 2020-08-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_user_associate_with_dorm_user_associate_with_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Associate_with_Dorm',
        ),
    ]
