# Generated by Django 3.0.8 on 2020-08-10 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_auto_20200809_1713'),
        ('security', '0007_delete_user_associate_with_dorm'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Associate_with_Dorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dorm', models.ForeignKey(on_delete=models.SET(0), to='organizations.Dorm')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
