# Generated by Django 3.0.8 on 2020-08-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_user_associate_with_dorm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.IntegerField(),
        ),
    ]
