# Generated by Django 3.0.8 on 2020-08-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_auto_20200810_1851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
