# Generated by Django 3.0.8 on 2020-11-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocked_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField(default='')),
                ('count', models.TextField(default=0)),
                ('ip', models.TextField(default='')),
                ('blocked', models.BooleanField(default=False)),
                ('blocking_time', models.TimeField(default=None)),
            ],
        ),
    ]
