# Generated by Django 3.0.8 on 2020-11-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0011_blocked_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blocked_Users',
            new_name='BlockedUsers',
        ),
    ]
