# Generated by Django 3.0.8 on 2020-12-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0012_auto_20201128_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedusers',
            name='blocking_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
